// Setup Server
const express = require('express');
const cors = require('cors');

const app = express();
// Dotenv Package (to setup environment variables)
const dotenv = require('dotenv');
dotenv.config();

// Dependencies
const bodyParser = require('body-parser');

// Middleware
app.use(bodyParser.urlencoded({
    extended: false
}));
app.use(bodyParser.json());
app.use(cors())
app.use(express.static('dist'));

//Port and routes

const port = 8080;
const server = app.listen(port, () => {
    console.log(`Server running on http://localhost:${port}`);
});

     //API keys variables
     const geonamesAPIKey =process.env.GEONAMES_API_KEY
     const pixabayAPIKey = process.env.PIXABAY
     const weatherbitAPIKey = process.env.WEATHERBIT 

let projectGeonamesData =[]
let data = []
app.post('/api', async (req,res)=>{
    data.push(req.body);
    console.log(`Data from client is ${data}`)
    const destination =data[0].destination
    console.log(destination)
    //Type here what you want to do in your post
        //API fetch to get lat, long and country name from Geonames API
        //Don't forget to change Milano with destination
        const response = await fetch (`http://api.geonames.org/searchJSON?name=Milano&maxRows=1&username=${geonamesAPIKey}`) //fetching data from the API
        .then(res => res.json()) //this converts data to json format
        .then(data => {
            console.log(data); //display data in the console for debugging
            const geonamesData = data //variable to store data generated by API
            projectGeonamesData.push(geonamesData) //pushing data generated nby API to the projectGeonamesData 
            console.log("This our geonames project data:") //debugging purpose
            console.log(projectGeonamesData) //debugging purpose
            res.send(data) // This sends the data to the client side
        })
        .catch(error =>console.log('error')) //Catching errors in the code
    

    //API call for weatherbit
    try{
    }catch(error){console.log("Error in the API call for weather")}
    })
// Define a route for serving the HTML file
app.get('/', (req, res) => {
    res.sendFile('dist/index.html'); // Change the path to your HTML file
});

